---
abstract: 'Contact-related value objects'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Value-Contact
provides:
  Class::Value::Contact:
    file: lib/Class/Value/Contact.pm
    version: 1.100840
  Class::Value::Contact::Address:
    file: lib/Class/Value/Contact/Address.pm
    version: 1.100840
  Class::Value::Contact::Address::Apartment:
    file: lib/Class/Value/Contact/Address/Apartment.pm
    version: 1.100840
  Class::Value::Contact::Address::City:
    file: lib/Class/Value/Contact/Address/City.pm
    version: 1.100840
  Class::Value::Contact::Address::Country:
    file: lib/Class/Value/Contact/Address/Country.pm
    version: 1.100840
  Class::Value::Contact::Address::State:
    file: lib/Class/Value/Contact/Address/State.pm
    version: 1.100840
  Class::Value::Contact::Address::Street:
    file: lib/Class/Value/Contact/Address/Street.pm
    version: 1.100840
  Class::Value::Contact::Address::Streetnumber:
    file: lib/Class/Value/Contact/Address/Streetnumber.pm
    version: 1.100840
  Class::Value::Contact::Address::Zip:
    file: lib/Class/Value/Contact/Address/Zip.pm
    version: 1.100840
  Class::Value::Contact::CompanyNo:
    file: lib/Class/Value/Contact/CompanyNo.pm
    version: 1.100840
  Class::Value::Contact::EmailAddress:
    file: lib/Class/Value/Contact/EmailAddress.pm
    version: 1.100840
  Class::Value::Contact::EmailAddress_TEST:
    file: lib/Class/Value/Contact/EmailAddress_TEST.pm
    version: 1.100840
  Class::Value::Contact::Exception:
    file: lib/Class/Value/Contact/Exception.pm
    version: 1.100840
  Class::Value::Contact::Exception::Email:
    file: lib/Class/Value/Contact/Exception/Email.pm
    version: 1.100840
  Class::Value::Contact::Exception::Email::Invalid:
    file: lib/Class/Value/Contact/Exception/Email/Invalid.pm
    version: 1.100840
  Class::Value::Contact::Exception::Email::NotWellformed:
    file: lib/Class/Value/Contact/Exception/Email/NotWellformed.pm
    version: 1.100840
  Class::Value::Contact::Exception::Invalid:
    file: lib/Class/Value/Contact/Exception/Invalid.pm
    version: 1.100840
  Class::Value::Contact::Exception::InvalidCountry:
    file: lib/Class/Value/Contact/Exception/InvalidCountry.pm
    version: 1.100840
  Class::Value::Contact::Exception::InvalidFaxNo:
    file: lib/Class/Value/Contact/Exception/InvalidFaxNo.pm
    version: 1.100840
  Class::Value::Contact::Exception::InvalidPhoneNo:
    file: lib/Class/Value/Contact/Exception/InvalidPhoneNo.pm
    version: 1.100840
  Class::Value::Contact::Exception::Name:
    file: lib/Class/Value/Contact/Exception/Name.pm
    version: 1.100840
  Class::Value::Contact::Exception::Name::Invalid:
    file: lib/Class/Value/Contact/Exception/Name/Invalid.pm
    version: 1.100840
  Class::Value::Contact::Exception::Name::NotWellformed:
    file: lib/Class/Value/Contact/Exception/Name/NotWellformed.pm
    version: 1.100840
  Class::Value::Contact::Exception::NotWellformed:
    file: lib/Class/Value/Contact/Exception/NotWellformed.pm
    version: 1.100840
  Class::Value::Contact::Exception::Replace:
    file: lib/Class/Value/Contact/Exception/Replace.pm
    version: 1.100840
  Class::Value::Contact::Exception::ReplaceAliasCountry:
    file: lib/Class/Value/Contact/Exception/ReplaceAliasCountry.pm
    version: 1.100840
  Class::Value::Contact::Exception::ReplaceFaxNo:
    file: lib/Class/Value/Contact/Exception/ReplaceFaxNo.pm
    version: 1.100840
  Class::Value::Contact::Exception::ReplacePhoneNo:
    file: lib/Class/Value/Contact/Exception/ReplacePhoneNo.pm
    version: 1.100840
  Class::Value::Contact::FaxNumber:
    file: lib/Class/Value/Contact/FaxNumber.pm
    version: 1.100840
  Class::Value::Contact::Name::Firstname:
    file: lib/Class/Value/Contact/Name/Firstname.pm
    version: 1.100840
  Class::Value::Contact::Name::Full:
    file: lib/Class/Value/Contact/Name/Full.pm
    version: 1.100840
  Class::Value::Contact::Name::Full_TEST:
    file: lib/Class/Value/Contact/Name/Full_TEST.pm
    version: 1.100840
  Class::Value::Contact::Name::Lastname:
    file: lib/Class/Value/Contact/Name/Lastname.pm
    version: 1.100840
  Class::Value::Contact::Name::Title:
    file: lib/Class/Value/Contact/Name/Title.pm
    version: 1.100840
  Class::Value::Contact::Organization:
    file: lib/Class/Value/Contact/Organization.pm
    version: 1.100840
  Class::Value::Contact::PhoneLikeNumber:
    file: lib/Class/Value/Contact/PhoneLikeNumber.pm
    version: 1.100840
  Class::Value::Contact::PhoneNumber:
    file: lib/Class/Value/Contact/PhoneNumber.pm
    version: 1.100840
  Class::Value::Contact::URL:
    file: lib/Class/Value/Contact/URL.pm
    version: 1.100840
requires:
  Carp: 0
  Class::Value::Exception::Base: 0
  Class::Value::String: 0
  Class::Value::Test: 0
  Email::Valid: 0
  English: 0
  Error::Hierarchy::Util: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::CompanionClasses: 0
  Test::More: 0.88
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Class-Value-Contact
  homepage: http://search.cpan.org/dist/Class-Value-Contact/
  repository: http://github.com/hanekomu/Class-Value-Contact
version: 1.100840
